language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

script: ./vendor/bin/tester -s -p php -c ./tests/php.ini-unix ./tests/CarrooiTests/

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist --prefer-lowest --prefer-stable

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
